# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master]
env:
    PORT: 2000
    NODE_ENV: ${{secrets.NODE_ENV}}
    DB_URI_CLOUD: ${{secrets.DB_URI_CLOUD}}
    DB_URI_LOCAL: ${{secrets.DB_URI_LOCAL}}
    JWT_SECRET: ${{secrets.JWT_SECRET}}
    CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
    CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
    CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
    MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}
    MAILGUN_EMAIL_DOMAIN: ${{secrets.MAILGUN_EMAIL_DOMAIN}}
    MAIL_SEND_ENABLE: ${{secrets.MAIL_SEND_ENABLE}}

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build --if-present
            - run: pm2 restart space-backend -a
