# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master]
env:
    PORT: 2000
    NODE_ENV: ${{secrets.NODE_ENV}}
    DB_URI_CLOUD: ${{secrets.DB_URI_CLOUD}}
    DB_URI_LOCAL: ${{secrets.DB_URI_LOCAL}}
    JWT_SECRET: ${{secrets.JWT_SECRET}}
    CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
    CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
    CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
    SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
    SENDGRID_VERIFIED_SENDER: ${{secrets.SENDGRID_VERIFIED_SENDER}}
    MAIL_SEND_ENABLE: ${{secrets.MAIL_SEND_ENABLE}}
    TEMPLATE_ID_EMAIL_VERIFY: ${{secrets.TEMPLATE_ID_EMAIL_VERIFY}}
    TEMPLATE_ID_WELCOME_MAIL: ${{secrets.TEMPLATE_ID_WELCOME_MAIL}}
    TEMPLATE_ID_RESEND_VERIFY_CODE: ${{secrets.TEMPLATE_ID_RESEND_VERIFY_CODE}}
    TEMPLATE_ID_FORGET_PASSWORD: ${{secrets.TEMPLATE_ID_FORGET_PASSWORD}}
    TEMPLATE_ID_ASSIGN_TASK: ${{secrets.TEMPLATE_ID_ASSIGN_TASK}}
    TEMPLATE_ID_MEMBER_ADD_IN_WORKSPACE: ${{secrets.TEMPLATE_ID_MEMBER_ADD_IN_WORKSPACE}}
    TEMPLATE_ID_MENTION_IN_CHAT: ${{secrets.TEMPLATE_ID_MENTION_IN_CHAT}}
    TEMPLATE_ID_MENTION_IN_TASK_COMMENT: ${{secrets.TEMPLATE_ID_MENTION_IN_TASK_COMMENT}}

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - run: npm run build --if-present
            - run: pm2 restart betasquad-backend -a
